# Generated by Django 5.2.13 on 2026-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(default='workday', max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen', 'company', 'title'],
                'indexes': [models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'), models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'), models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx')],
            },
        ),
    ]
