# Generated by Django 5.2.14 on 2026-05-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_posted_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_posted__0a7770_idx',
            old_name='jobs_job_posted__e9488e_idx',
        ),
    ]
