"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

import dj_database_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&4jn8c)9-_-%5jpvb$v(i5kq8d-64=8g&zjs^p0)hvzgx-a4k*')

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*']

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jobs.apps.JobsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('POSTGRES_DB') or os.environ.get('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'untitled_project'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

WORKDAY_SITES = [
    {
        'company': 'KION Group',
        'url': 'https://kiongroup.wd3.myworkdayjobs.com/en-US/KION_SCS',
    },
    {
        'company': 'HPE',
        'url': 'https://hpe.wd5.myworkdayjobs.com/en-US/Jobsathpe',
    },
    {
        'company': 'Blue Origin',
        'url': 'https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin',
    },
    {
        'company': 'Community Brands',
        'url': 'https://communitybrands.wd1.myworkdayjobs.com/en-US/Momentive_External_Careers',
    },
    {
        'company': 'General Motors',
        'url': 'https://generalmotors.wd5.myworkdayjobs.com/Careers_GM',
    },
    {
        'company': 'Boeing',
        'url': 'https://boeing.wd1.myworkdayjobs.com/EXTERNAL_CAREERS',
    },
    {
        'company': 'NVIDIA',
        'url': 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite',
    },
    {
        'company': '3M',
        'url': 'https://3m.wd1.myworkdayjobs.com/Search',
    },
    {
        'company': 'Raytheon Technologies',
        'url': 'https://globalhr.wd5.myworkdayjobs.com/en-US/REC_RTX_Ext_Gateway',
    },
    {
        'company': 'Salesforce',
        'url': 'https://salesforce.wd12.myworkdayjobs.com/en-US/External_Career_Site',
    },
    {
        'company': 'Workday',
        'url': 'https://workday.wd5.myworkdayjobs.com/Workday/',
    },
    {
        'company': 'Motorola Solutions',
        'url': 'https://motorolasolutions.wd5.myworkdayjobs.com/Careers',
    },
    {
        'company': 'Intel',
        'url': 'https://intel.wd1.myworkdayjobs.com/External',
    },
    {
        'company': 'Caterpillar',
        'url': 'https://cat.wd5.myworkdayjobs.com/en-US/CaterpillarCareers',
    },
    {
        'company': 'Applied Materials',
        'url': 'https://amat.wd1.myworkdayjobs.com/External',
    },
    {
        'company': 'Auto-Owners Insurance',
        'url': 'https://aoins.wd5.myworkdayjobs.com/AutoOwners',
    },
    {
        'company': 'Abbott',
        'url': 'https://abbott.wd5.myworkdayjobs.com/en-US/abbottcareers',
    },
    {
        'company': 'GPC',
        'url': 'https://genpt.wd1.myworkdayjobs.com/en-US/Careers',
    },
    {
        'company': 'Abbott',
        'url': 'https://abbott.wd5.myworkdayjobs.com/en-US/abbottcareers'
    },
    {
        'company': 'Huntington National Bank',
        'url': 'https://huntington.wd12.myworkdayjobs.com/en-US/HNBcareers'
    },
    {
        'company': 'SNC',
        'url': 'https://snc.wd1.myworkdayjobs.com/en-US/SNC_External_Career_Site'
    },
    {
        'company': 'Logitech',
        'url': 'https://logitech.wd5.myworkdayjobs.com/en-US/Logitech/jobs'
    },
    {
        'company': 'Grubhub',
        'url' : 'https://wonder.wd1.myworkdayjobs.com/en-US/Grubhub_Careers'
    },
    {
        'company': 'Philips',
        'url': 'https://philips.wd3.myworkdayjobs.com/en-US/jobs-and-careers'
    },
    {
        'company': 'Magna',
        'url': 'https://wd3.myworkdaysite.com/recruiting/magna/Magna'
    },
    {
        'company': 'Boston Dynamics',
        'url': 'https://bostondynamics.wd1.myworkdayjobs.com/en-US/Boston_Dynamics'
    },
]

LEVER_SITES = [
    {
        'company': 'Zoox',
        'url': 'https://jobs.lever.co/zoox/',
    },
    {
        'company': 'Mistral',
        'url': 'https://jobs.lever.co/mistral/',
    },
    {
        'company': 'Lumafield',
        'url': 'https://jobs.lever.co/lumafield/',
    },
    {
        'company': 'Revel',
        'url': 'https://jobs.lever.co/revel/',
    },
    {
        'company': 'FloQast',
        'url': 'https://jobs.lever.co/floqast',
    },
    {
        'company': 'Shield AI',
        'url': 'https://jobs.lever.co/shieldai',
    },
    {
        'company': 'PointClickCare',
        'url': 'https://jobs.lever.co/pointclickcare',
    },
    {
        'company': 'Zeta',
        'url': 'https://jobs.lever.co/zeta',
    },
    {
        'company': 'GoodLeap',
        'url': 'https://jobs.lever.co/goodleap',
    },
    {
        'company': 'Palantir',
        'url': 'https://jobs.lever.co/palantir',
    },
]

ASHBY_SITES = [
    {
        'company': 'Mach',
        'url': 'https://jobs.ashbyhq.com/mach',
    },
    {
        'company': 'Notion',
        'url': 'https://jobs.ashbyhq.com/notion',
    },
    {
        'company': 'Ramp',
        'url': 'https://jobs.ashbyhq.com/ramp',
    },
    {
        'company': 'Clay Labs',
        'url': 'https://jobs.ashbyhq.com/claylabs',
    },
    {
        'company': 'Etched',
        'url': 'https://jobs.ashbyhq.com/etched',
    },
    {
        'company': 'Apex Technology',
        'url': 'https://jobs.ashbyhq.com/apex-technology-inc/',
    },
    {
        'company': 'Open Loop Health',
        'url': 'https://jobs.ashbyhq.com/openloophealth',
    },
    {
        'company': 'Form Energy',
        'url': 'https://jobs.ashbyhq.com/formenergy/',
    },
    {
        'company': 'Sesame',
        'url': 'https://jobs.ashbyhq.com/sesame/',
    },
    {
        'company': 'OpenAI',
        'url': 'https://jobs.ashbyhq.com/openai',
    },
    {
        'company': 'Crusoe',
        'url': 'https://jobs.ashbyhq.com/Crusoe',
    },
]

JOBVITE_SITES = [
    {
        'company': 'Tyler Tech',
        'url' : 'https://jobs.jobvite.com/tylertech/jobs'
    },
    {
        'company': 'Gigamon',
        'url': 'https://jobs.jobvite.com/gigamon/job'
    }
]

APPLY_SITES = [
    {
        'company': 'Ford',
        'url': 'https://apply.ford.com/en/sites/CX_1/jobs'
    }
]

GREENHOUSE_SITES = [
    {
        'company': 'Two Six Technologies',
        'url': 'https://job-boards.greenhouse.io/twosixtechnologies',
    },
    {
        'company': 'Applied Intuition',
        'url': 'https://job-boards.greenhouse.io/appliedintuition',
    },
    {
        'company': 'RunPod',
        'url': 'https://job-boards.greenhouse.io/runpod',
    },
    {
        'company': 'Next Insurance',
        'url': 'https://job-boards.greenhouse.io/nextinsurance66',
    },
    {
        'company': 'Reddit',
        'url': 'https://job-boards.greenhouse.io/reddit',
    },
    {
        'company': 'Tailscale',
        'url': 'https://job-boards.greenhouse.io/tailscale/',
    },
    {
        'company': 'Jane Street',
        'url': 'https://job-boards.greenhouse.io/janestreet/',
    },
    {
        'company': 'Inversion Space',
        'url': 'https://job-boards.greenhouse.io/inversionspace',
    },
    {
        'company': 'Vercel',
        'url': 'https://job-boards.greenhouse.io/vercel',
    },
    {
        'company': 'Pure Storage',
        'url': 'https://job-boards.greenhouse.io/purestorage/',
    },
    {
        'company': 'MATX',
        'url': 'https://job-boards.greenhouse.io/matx',
    },
    {
        'company': 'Affirm',
        'url': 'https://job-boards.greenhouse.io/affirm'
    },
    {
        'company': 'Dataiku',
        'url': 'https://job-boards.greenhouse.io/dataiku/',
    },
    {
        'company': 'IMC',
        'url': 'https://job-boards.eu.greenhouse.io/imc',
    },
    {
        'company': 'Glean',
        'url': 'https://job-boards.greenhouse.io/gleanwork',
    },
    {
        'company': 'General Matter',
        'url': 'https://job-boards.greenhouse.io/generalmatter',
    },
    {
        'company': 'Tenstorrent',
        'url': 'https://job-boards.greenhouse.io/tenstorrent',
    },
    {
        'company': 'Automox',
        'url': 'https://job-boards.greenhouse.io/automox',
    },
    {
        'company': 'Thinking Machines',
        'url': 'https://job-boards.greenhouse.io/thinkingmachines',
    },
    {
        'company': 'Lightning AI',
        'url': 'https://job-boards.greenhouse.io/lightningai',
    },
    {
        'company': 'Imbue',
        'url': 'https://job-boards.greenhouse.io/imbue',
    },
    {
        'company': 'Cresta',
        'url': 'https://job-boards.greenhouse.io/cresta',
    },
    {
        'company': 'Avride',
        'url': 'https://job-boards.greenhouse.io/avride',
    },
    {
        'company': 'Loop',
        'url': 'https://job-boards.greenhouse.io/loop'
    },
    {
        'company': 'Underdog',
        'url': 'https://job-boards.greenhouse.io/underdogfantasy'
    },
    {
        'company': 'Oklo',
        'url': 'https://job-boards.greenhouse.io/oklo'
    },
    {
        'company': 'Verkada',
        'url': 'https://job-boards.greenhouse.io/verkada'
    },
    {
        'company': 'Scale AI',
        'url': 'https://job-boards.greenhouse.io/scaleAI'
    },
    {
        'company': 'Samsara',
        'url': 'https://job-boards.greenhouse.io/samsara'
    },
    {
        'company': 'Discord',
        'url': 'https://job-boards.greenhouse.io/discord'
    },
    {
        'company': 'Nuro',
        'url': 'https://job-boards.greenhouse.io/nuro'
    },
    {
        'company': 'Figma',
        'url': 'https://job-boards.greenhouse.io/figma'
    },
    {
        'company': 'Beyond Finance',
        'url': 'https://www.beyondfinance.com/careers/jobs/'
    },
    {
        'company': 'Lattice',
        'url': 'https://lattice.com/careers#open-positions'
    },
    {
        'company': 'Growtherapy',
        'url': 'https://job-boards.greenhouse.io/growtherapy',
    },
    {
        'company': 'Lila Sciences',
        'url': 'https://job-boards.greenhouse.io/lilasciences',
    },
    {
        'company': 'Twin Health',
        'url': 'https://job-boards.greenhouse.io/twinhealth',
    },
    {
        'company': 'Together AI',
        'url': 'https://job-boards.greenhouse.io/togetherai',
    },
    {
        'company': 'SHEIN',
        'url': 'https://job-boards.greenhouse.io/shein',
    },
    {
        'company': 'Warp',
        'url': 'https://job-boards.greenhouse.io/warp',
    },
    {
        'company': 'Divergent',
        'url': 'https://job-boards.greenhouse.io/divergent',
    },
    {
        'company': 'Scout Motors',
        'url': 'https://job-boards.greenhouse.io/scoutmotors',
    },
    {
        'company': 'Hightouch',
        'url': 'https://job-boards.greenhouse.io/hightouch',
    },
    {
        'company': 'Prismatic',
        'url': 'https://job-boards.greenhouse.io/prismatic',
    },
    {
        'company': 'Turbine One',
        'url': 'https://job-boards.greenhouse.io/turbineone',
    },
    {
        'company': 'Postman',
        'url': 'https://job-boards.greenhouse.io/postman',
    },
    {
        'company': 'Qualia',
        'url': 'https://job-boards.greenhouse.io/qualia',
    },
    {
        'company': 'Samsung Semiconductor',
        'url': 'https://job-boards.greenhouse.io/samsungsemiconductor',
    },
    {
        'company': 'Robinhood',
        'url': 'https://job-boards.greenhouse.io/robinhood',
    },
    {
        'company': 'AlphaSense',
        'url': 'https://job-boards.greenhouse.io/alphasense',
    },
    {
        'company': 'Checkr',
        'url': 'https://job-boards.greenhouse.io/checkr',
    },
    {
        'company': 'Carta',
        'url': 'https://job-boards.greenhouse.io/carta',
    },
    {
        'company': 'Freenome',
        'url': 'https://job-boards.greenhouse.io/freenome',
    },
    {
        'company': 'Omada Health',
        'url': 'https://job-boards.greenhouse.io/omadahealth',
    },
    {
        'company': 'Panther Labs',
        'url': 'https://job-boards.greenhouse.io/pantherlabs',
    },
    {
        'company': 'Heartflow',
        'url': 'https://job-boards.greenhouse.io/heartflowinc',
    },
    {
        'company': 'Snorkel AI',
        'url': 'https://job-boards.greenhouse.io/snorkelai',
    },
    {
        'company': 'DriveWealth',
        'url': 'https://job-boards.greenhouse.io/drivewealth',
    },
    {
        'company': 'TaxBit',
        'url': 'https://job-boards.greenhouse.io/taxbit',
    },
    {
        'company': 'Tanium',
        'url': 'https://job-boards.greenhouse.io/tanium',
    },
    {
        'company': 'Mercury',
        'url': 'https://job-boards.greenhouse.io/mercury',
    },
    {
        'company': 'Addepar',
        'url': 'https://job-boards.greenhouse.io/addepar1',
    },
    {
        'company': 'Roofstock',
        'url': 'https://job-boards.greenhouse.io/roofstock',
    },
    {
        'company': 'OneTrust',
        'url': 'https://job-boards.greenhouse.io/onetrust',
    },
    {
        'company': 'ZocDoc',
        'url': 'https://job-boards.greenhouse.io/zocdoc/jobs',
    },
    {
        'company': 'Extend',
        'url': 'https://job-boards.greenhouse.io/extend',
    },
    {
        'company': 'Cerebras Systems',
        'url': 'https://job-boards.greenhouse.io/cerebrassystems',
    },
    {
        'company': 'Spring Health',
        'url': 'https://job-boards.greenhouse.io/springhealth66',
    },
    {
        'company': 'Gusto',
        'url': 'https://job-boards.greenhouse.io/gusto',
    },
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
