"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&4jn8c)9-_-%5jpvb$v(i5kq8d-64=8g&zjs^p0)hvzgx-a4k*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jobs.apps.JobsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('POSTGRES_DB') or os.environ.get('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'untitled_project'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

WORKDAY_SITES = [
    {
        'company': 'General Motors',
        'url': 'https://generalmotors.wd5.myworkdayjobs.com/Careers_GM',
    },
    {
        'company': 'Boeing',
        'url': 'https://boeing.wd1.myworkdayjobs.com/EXTERNAL_CAREERS',
    },
    {
        'company': 'NVIDIA',
        'url': 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite',
    },
    {
        'company': '3M',
        'url': 'https://3m.wd1.myworkdayjobs.com/Search',
    },
    {
        'company': 'Raytheon Technologies',
        'url': 'https://globalhr.wd5.myworkdayjobs.com/en-US/REC_RTX_Ext_Gateway',
    },
    {
        'company': 'Salesforce',
        'url': 'https://salesforce.wd12.myworkdayjobs.com/en-US/External_Career_Site',
    },
    {
        'company': 'Workday',
        'url': 'https://workday.wd5.myworkdayjobs.com/Workday/',
    },
    {
        'company': 'Motorola Solutions',
        'url': 'https://motorolasolutions.wd5.myworkdayjobs.com/Careers',
    },
    {
        'company': 'Intel',
        'url': 'https://intel.wd1.myworkdayjobs.com/External',
    },
    {
        'company': 'Caterpillar',
        'url': 'https://cat.wd5.myworkdayjobs.com/en-US/CaterpillarCareers',
    },
    {
        'company': 'Applied Materials',
        'url': 'https://amat.wd1.myworkdayjobs.com/External',
    },
    {
        'company': 'Auto-Owners Insurance',
        'url': 'https://aoins.wd5.myworkdayjobs.com/AutoOwners',
    },
    {
        'company': 'Abbott',
        'url': 'https://abbott.wd5.myworkdayjobs.com/en-US/abbottcareers',
    },
    {
        'company': 'Booz Allen',
        'url': 'https://bah.wd1.myworkdayjobs.com/en-US/BAH_Jobs?redirect=/en-US/BAH_Jobs/userHome',
    },
    {
        'company': 'GPC',
        'url': 'https://genpt.wd1.myworkdayjobs.com/en-US/Careers',
    }
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
